services:
  - type: web
    name: hepsihikaye
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FLASK_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
